data:
  jpa.repositories.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      default_schema: canary-testing
      javax:
        persistence:
          validation:
            mode: none
  flyway:
    enabled: false
    locations: classpath:/db/migration
  datasource:
    driverClassName: org.postgresql.Driver
    continueOnError: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
server:
  port: 8080