#spring:
#  datasource:
#    platform: test
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  datasource.initialization-mode: always
canary:
  model:
    url: https://kongurl/path

spring:
  data:
    jpa.repositories.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
  flyway:
    enabled: false
    locations: classpath:/db/migration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:@project.artifactId@
    continueOnError: true