#spring:
#  datasource:
#    platform: test
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  datasource.initialization-mode: always
canary:
  model:
    url: https://kongurl/path
